services:
    solver:
        image: test_mpt:latest
        volumes:
            - ~/datasets:/data
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - /bin/bash
            - -c
            - tail -f /dev/null

networks:
    default:
        driver: bridge
        name: solvenet

