services:
    solver:
        image: test_mpt:latest
        tty: true
        volumes:
            - ~/datasets:/data
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - /bin/bash
            - python3 /mpt/demo/time_script.py

networks:
    default:
        driver: bridge
        name: solvenet

